# Generated by Django 4.2.7 on 2023-11-20 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('image', models.SlugField(default='', max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(default='study', max_length=16)),
                ('copyright_year', models.CharField(default='', max_length=4)),
                ('last_update', models.DateField(default=datetime.date.today)),
                ('lede', models.CharField(max_length=250)),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('archive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entry.archive')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
