# Generated by Django 2.1.2 on 2018-10-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnihanCharacter',
            fields=[
                ('codepoint', models.IntegerField(primary_key=True, serialize=False)),
                ('definition', models.TextField(max_length=1000)),
                ('mandarin', models.CharField(max_length=20)),
                ('residual_strokes', models.IntegerField()),
                ('simplified_variants', models.CharField(max_length=10)),
                ('traditional_variants', models.CharField(max_length=10)),
                ('semantic_variants', models.CharField(max_length=10)),
                ('sort_order', models.IntegerField()),
                ('utf8', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='UnihanRadical',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='unihan.UnihanCharacter')),
                ('radical_number', models.IntegerField()),
                ('simplified', models.BooleanField()),
                ('utf8', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Radical',
                'verbose_name_plural': 'Radicals',
            },
        ),
        migrations.AddField(
            model_name='unihancharacter',
            name='radical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unihan.UnihanRadical'),
        ),
    ]
