# Generated by Django 2.2.6 on 2019-10-20 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(default=datetime.date.today)),
                ('lede', models.CharField(max_length=250)),
                ('published', models.BooleanField()),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
