# Generated by Django 3.1.5 on 2021-01-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.archive'),
        ),
    ]
