# Generated by Django 3.1.5 on 2021-02-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210119_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='allow_hanzi',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(default='study', max_length=16),
        ),
    ]
