# Generated by Django 3.1.7 on 2021-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210201_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
